// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEGM3GZpgv80XoOnQvGdTDTJO0w9-Ybxo',
    appId: '1:466308218787:web:d1a37a9df1a98589e4e416',
    messagingSenderId: '466308218787',
    projectId: 'apexclouds-ed3df',
    authDomain: 'apexclouds-ed3df.firebaseapp.com',
    storageBucket: 'apexclouds-ed3df.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtQuHknAZvcgd1bMgqn2LVX-eRhclZ5dA',
    appId: '1:466308218787:android:8578a6360ec7d1d3e4e416',
    messagingSenderId: '466308218787',
    projectId: 'apexclouds-ed3df',
    storageBucket: 'apexclouds-ed3df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbne5CSeSosQv43J7Ju25aIB_WQNZzUpw',
    appId: '1:466308218787:ios:6acb29c442fcd4f5e4e416',
    messagingSenderId: '466308218787',
    projectId: 'apexclouds-ed3df',
    storageBucket: 'apexclouds-ed3df.appspot.com',
    iosClientId: '466308218787-fptdsod3ofh6g4a4hh3ft0jj577du67u.apps.googleusercontent.com',
    iosBundleId: 'com.example.apexClouds',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbne5CSeSosQv43J7Ju25aIB_WQNZzUpw',
    appId: '1:466308218787:ios:6acb29c442fcd4f5e4e416',
    messagingSenderId: '466308218787',
    projectId: 'apexclouds-ed3df',
    storageBucket: 'apexclouds-ed3df.appspot.com',
    iosClientId: '466308218787-fptdsod3ofh6g4a4hh3ft0jj577du67u.apps.googleusercontent.com',
    iosBundleId: 'com.example.apexClouds',
  );
}
